apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::374493580790:role/UdacityFlaskDeployCBKubectlRole
      username: build 
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::374493580790:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-3JU7TOWORIKU
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2022-01-10T06:42:16Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1401"
  uid: 6027e41e-15e6-4f12-a313-edca1acc5d05
